config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
                                   controllers: { sessions: 'users/sessions' }


  resources :tests, only: :index do
    member do 
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do 
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges
    resources :gists
    resources :tests do
      patch :update_inline, on: :member
      
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end  
    end
  end

  namespace :users do
    resources :feedbacks, only: [:new, :create]
    resources :badges, only: [:index]
  end
end

app/models/admin.rb
class Admin < User

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_answers_quantity, on: :create

  MAX_ANSWERS = 4

  scope :correct, -> { where(correct: true) }

  private

  def validate_answers_quantity
    if question && question.answers.size > MAX_ANSWERS
      errors.add(:answers_quantity, "error: question can have not more then 4 answers")
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :tests, dependent: :destroy

  validates :title, presence: true

  default_scope { order(title: :asc) }
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy 
  has_many :gists, dependent: :destroy 

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  has_many :questions, dependent: :destroy 
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages
  belongs_to :author, foreign_key: "user_id", class_name: 'User', optional: true

  validates :title, presence: true, uniqueness: {scope: :level}
  validates :level, numericality: {only_integer: true, greater_than_or_equal_to: 0}

  scope :level_sort, -> (level) { where(level: level) }
  scope :easy, -> { level_sort(0..1) }
  scope :medium, -> { level_sort(2..4) }
  scope :hard, -> { level_sort(5..Float::INFINITY) }


  scope :tests_by_category_title, -> (category_title) { joins('JOIN categories ON categories.id = tests.category_id')
    .where('categories.title = ?', category_title) }
  
  scope :user_succeed_tests, -> (user_id) { joins('JOIN test_passages ON test_passages.test_id = tests.id')
                                              .where('test_passages.user_id = ?', user_id)
                                              .where('test_passages.succeed = true') }
  
  scope :category, -> (category_id) { where(category: category_id) }
  
  def self.sorted_category(category)
    tests_by_category(category).order(title: :desc).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_update :before_update_set_next_question
  before_save :succeed!
  
  SUCCESS_RESULT = 85

  def completed?
    current_question.nil?
  end

  def success?
    result >= SUCCESS_RESULT
  end

  def succeed!
    self.succeed = true if success?
  end

  def time_out?
    DateTime.now.to_i >= expire_time
  end


  def expire_time
    self.created_at.to_i + test.timer
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end
  
    save!
  end

  def result
    ((correct_questions.to_f / test.questions.count.to_f ) * 100).round(2) 
  end

  def current_question_number
    test.questions.order(:id).index(current_question) + 1
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    if answer_ids
      correct_answers.ids.sort == answer_ids.map(&:to_i).sort
    else
      false
    end  
  end
  
  def correct_answers
    current_question.answers.correct
  end

  def before_update_set_next_question
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first
  end

end

app/models/tests_user.rb
class TestsUser < ApplicationRecord
  belongs_to :user
  belongs_to :test   
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :registerable,
         :recoverable, 
         :rememberable, 
         :validatable,
         :confirmable

  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :created_tests, inverse_of: 'author', class_name: 'Test'
  has_many :gists
  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                    format: { with: VALID_EMAIL_REGEX, message: "Invalid email format" },
                    uniqueness: true
  
  def test_level(test_level)
    self.tests.where(level: test_level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    self.type == "Admin"
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(test, question)
    if question.new_record?
      "Create question for test: #{test.title}"
    else
      "Edit question in test: #{question.test.title} "
    end
  end 
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_nav.html.erb
  <nav class="navbar navbar-light bg-info">
   <h1><%= link_to "TestGuru", root_path, class: 'navbar-brand' %></h1>
    Admin Panel
    <div class="navbar-text">
      <% if user_signed_in? %>
        <p><%= link_to "Gists", admin_gists_path %></p>
        <p><%= link_to "Badges", admin_badges_path %></p>
        </div>
        <p class="nav user">Welcome, <b> <%= current_user.email %></b> Guru |  
        <%= link_to "Logout", destroy_user_session_path, method: :delete %></p>
      <% else %>
        <%= link_to "Log in", new_session_path(resource_name) %> |
        <%= link_to "Sign up", new_registration_path(resource_name) %>
      <% end %>
    </span>
  </nav>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <h2>
      <%= t('.header', count: resource.errors.count) %>:
    </h2>

    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>  
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <% if key == "notice" %>
    <%= content_tag :p, message, class: "alert alert-success", role: "alert" %>
  <% else %>
    <%= content_tag :p, message, class: "alert alert-warning", role: "alert" %>
  <% end %>
<% end %>  

app/views/shared/_footer.html.erb
<footer class="navbar fixed-bottom bg-info">
 <div>
  <%= current_year %>, Евгений Остапенко
  <%= github_url("test-guru", "https://github.com/Evgeniy-github-acc/test-guru") %>
  - Учебный проект онлайн школы <a href="https://thinknetica.com" target="_blank">Thinknetica</a>
 </div>
</footer>

app/views/shared/_nav.html.erb
  <nav class="navbar navbar-light bg-info">
    <%= link_to "TestGuru", root_path, class: 'navbar-brand' %>
    
    <span class="navbar-text">
      <% if user_signed_in? %>
       
        <%= link_to "AdminPanel", admin_tests_path,  {:class => 'btn btn-light' } if current_user.admin? %>
       
        <p class="nav user"> Welcome, <b><%= current_user.email %></b> Guru |  
        <%= link_to " Logout", destroy_user_session_path, method: :delete %></p>
         <%= link_to "Feedback", new_users_feedback_path %>
         <%= link_to "My badges", users_badges_path %>         
      <% else %>
        <%= link_to "Log in", new_session_path(resource_name) %> |
        <%= link_to "Sign up", new_registration_path(resource_name) %>
      <% end %>
     </span>
  </nav>