config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
                                   controllers: { sessions: 'users/sessions' }


  resources :tests, only: :index do
    member do 
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do 
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges
    resources :gists
    resources :tests do
      patch :update_inline, on: :member
      
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end  
    end
  end

  namespace :users do
    resources :feedbacks, only: [:new, :create]
    resources :badges, only: [:index]
  end
end

app/models/admin.rb
class Admin < User

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_answers_quantity, on: :create

  MAX_ANSWERS = 4

  scope :correct, -> { where(correct: true) }

  private

  def validate_answers_quantity
    if question && question.answers.size > MAX_ANSWERS
      errors.add(:answers_quantity, "error: question can have not more then 4 answers")
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :tests, dependent: :destroy

  validates :title, presence: true

  default_scope { order(title: :asc) }
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy 
  has_many :gists, dependent: :destroy 

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  has_many :questions, dependent: :destroy 
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages
  belongs_to :author, foreign_key: "user_id", class_name: 'User', optional: true

  validates :title, presence: true, uniqueness: {scope: :level}
  validates :level, numericality: {only_integer: true, greater_than_or_equal_to: 0}

  scope :level_sort, -> (level) { where(level: level) }
  scope :easy, -> { level_sort(0..1) }
  scope :medium, -> { level_sort(2..4) }
  scope :hard, -> { level_sort(5..Float::INFINITY) }


  scope :tests_by_category_title, -> (category_title) { joins('JOIN categories ON categories.id = tests.category_id')
    .where('categories.title = ?', category_title) }
  
  scope :user_succeed_tests, -> (user_id) { joins('JOIN test_passages ON test_passages.test_id = tests.id')
                                              .where('test_passages.user_id = ?', user_id)
                                              .where('test_passages.succeed = true') }
  
  scope :category, -> (category_id) { where(category: category_id) }
  
  def self.sorted_category(category)
    tests_by_category(category).order(title: :desc).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_update :before_update_set_next_question
  before_save :succeed!
  
  SUCCESS_RESULT = 85

  def completed?
    current_question.nil?
  end

  def success?
    result >= SUCCESS_RESULT
  end

  def succeed!
    self.succeed = true if success?
  end

  def time_out?
    DateTime.now.to_i >= expire_time
  end


  def expire_time
    self.created_at.to_i + test.timer
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end
  
    save!
  end

  def result
    ((correct_questions.to_f / test.questions.count.to_f ) * 100).round(2) 
  end

  def current_question_number
    test.questions.order(:id).index(current_question) + 1
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    if answer_ids
      correct_answers.ids.sort == answer_ids.map(&:to_i).sort
    else
      false
    end  
  end
  
  def correct_answers
    current_question.answers.correct
  end

  def before_update_set_next_question
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first
  end

end

app/models/tests_user.rb
class TestsUser < ApplicationRecord
  belongs_to :user
  belongs_to :test   
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :registerable,
         :recoverable, 
         :rememberable, 
         :validatable,
         :confirmable

  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :created_tests, inverse_of: 'author', class_name: 'Test'
  has_many :gists
  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                    format: { with: VALID_EMAIL_REGEX, message: "Invalid email format" },
                    uniqueness: true
  
  def test_level(test_level)
    self.tests.where(level: test_level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    self.type == "Admin"
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update result gist]
  
  def show
  
  end

  def result
    check_badges = BadgeAssignmentService.new(current_user, @test_passage)
    check_badges.assignment
    @got_badges = check_badges.new_badges
  end

  def gist
    result = GistQuestionService.new(@test_passage.current_question)
    result.call

      if result.success?
        flash_options =  { notice: t('.success', link: result.gist_url) }
        current_user.gists.create(body: result.gist_url, question_id: @test_passage.current_question_id) 
      else
        flash_options = { alert: t('.failure') }
      end

    redirect_to @test_passage, flash_options
  end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed? || @test_passage.time_out?
  
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else  
      render :show
    end
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def current_year
    Time.zone.now.year
  end

  def github_url(repo, link)
    link_to repo, link, target: :_blank
  end

  def flash_message(event)
    flash[event.to_sym]
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(test, question)
    if question.new_record?
      "Create question for test: #{test.title}"
    else
      "Edit question in test: #{question.test.title} "
    end
  end 
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/test_passages/result.html.erb
  <div class="row justify-content-center">
    <div class="col col-md-10">
    <h3><%= t('.header', title: @test_passage.test.title) %></h3>
      <div class="card">
        <div class="card-body">
          <% if @test_passage.success? %>
            <p>You have successfully passed the test!</p>
            <p class="succeed">Your result: <%= @test_passage.result %>%</p>
          <% else %>
            <p>You didn't pass the test.</p>
            <p class="not_succeed">Your result: <%= @test_passage.result %>%</p>
          <% end %>
          <% if @test_passage.time_out? %>
            <p class="not_succeed"> Your time expired </p>
          <% end %>  
          <div>
          <div>
            <% if @got_badges %>
              <% @got_badges.each do |badge| %>
                <p><%= image_tag badge.file, size:"50x50" %></p>
                <p><%= "You earn #{badge.name} badge" %></p>
              <% end %>
            <% end %>  
          </div>
            <%= link_to "All tests", tests_path, class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <div>  
  </div>  

app/views/test_passages/show.html.erb
<div class="row justify-content-center">
  <div class="col col-md-10">
  <%= render 'shared/errors', resource: @test_passage %>
  <h3>Passing the <%= @test_passage.test.title %> Test</h3>  
    <div class="card">
      <div class="card-header">
       
            <%= content_tag :div, '', id:'timer', class: 'float-right',
            data: {test_time: @test_passage.test.timer, 
                   question_count: @test_passage.current_question_number} %>
           
            <p>Question <%= @test_passage.current_question_number %> of
           <%= @test_passage.test.questions.count %></p>
           <b><%= @test_passage.current_question.body %></b>
             
      </div>

      <div class="card-body">
           <%= form_with url: test_passage_path(@test_passage), local: true, method: :put, class: 'test-passage' do |form| %>
            <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
          
            <div class="form-check">  
              <label class="form-check-label">
                <%= b.check_box id: "answer_ids_#{b.object.id}", class: "form-check-input" %>
                <%= b.label %>
              </label>
            </div>  
          
            <% end %>
            <%= link_to 'Gist Question', gist_test_passage_path(@test_passage), method: :post, class: "btn btn-alert" %>
            <%= form.submit 'Next', class: "btn btn-primary" %>
          <% end %>
        <%= content_tag :progress, 'Progress', class: 'progress mt-2', 
            data: { progress_value: @test_passage.current_question_number },
            max: @test_passage.test.questions.count %>   
    </div>      
  </div>
 </div>