config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
                                   controllers: { sessions: 'users/sessions' }


  resources :tests, only: :index do
    member do 
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do 
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges
    resources :gists
    resources :tests do
      patch :update_inline, on: :member
      
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end  
    end
  end

  namespace :users do
    resources :feedbacks, only: [:new, :create]
    resources :badges, only: [:index]
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_answers_quantity, on: :create

  MAX_ANSWERS = 4

  scope :correct, -> { where(correct: true) }

  private

  def validate_answers_quantity
    if question && question.answers.size > MAX_ANSWERS
      errors.add(:answers_quantity, "error: question can have not more then 4 answers")
    end
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :authenticate_user!
  before_action :define_question, only: %i[new create]
  before_action :set_answer, only: %i[ show edit update destroy ]

  def show
  end

  def new
    @answer = @question.answers.new
  end

  def edit
  end

  def create
    @answer = @question.answers.new(answer_params)
    
    if @answer.save
      redirect_to admin_question_path(@question), notice: "Answer was successfully created."
    else
     render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_question_path(@answer.question), notice: "Answer was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_question_path(@answer.question), notice: "Answer was successfully destroyed." 
  end

  private
    
    def define_question
      @question = Question.find(params[:question_id])
    end  
    
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def answer_params
      params.require(:answer).permit(:body, :correct)
    end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :define_question, only: %i[new create]
  before_action :set_answer, only: %i[ show edit update destroy ]

  def show
  end

  def new
    @answer = @question.answers.new
  end

  def edit
  end

  def create
    @answer = @question.answers.new(answer_params)
    
    if @answer.save
      redirect_to @answer, notice: "Answer was successfully created."
    else
     render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to @answer, notice: "Answer was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @answer.destroy
    redirect_to @answer.question, notice: "Answer was successfully destroyed." 
  end

  private
    
    def define_question
      @question = Question.find(params[:question_id])
    end  
    
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def answer_params
      params.require(:answer).permit(:body, :correct)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<li>
  <%= answer.body %><br>
  <%= link_to 'Show', answer_path(answer) %> |
  <%= link_to 'Edit', edit_answer_path(answer) %> |
  <%= link_to 'Delete', 
              answer_path(answer), 
              method: :delete,
              data: {confirm: 'Are you sure?'} %> 
</li>

app/views/answers/_form.html.erb
<%= form_with model: [@question, @answer], local:true do |form| %>

  <p>
    <%= form.label :body %>
    <%= form.text_area :body, id: :anwer_body, rows: 7, cols: 60 %>
  </p>

  <p>
    <%= form.label :correct %>
    <%= form.check_box :correct, id: :answer_correct %>
  </p>

  <p><%= form.submit %></p>

<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>


<p>
  <%= @answer.question.body %>
</p>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', question_path(@anwer.question) %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<p>
  <%= @question.body %>
</p>

<%= render 'form' %>

<%= link_to 'Back', question_path(@question) %>

app/views/answers/show.html.erb
<h1>Question</h1>
<p>
  <%= @answer.question.body %>
</p>

<p>
  <b>Answer:</b>
  <%= @answer.body %>
</p>

<p>
  <b>Correct:</b>
  <%= @answer.correct %>
</p>

<%= link_to 'Back', question_path(@answer.question) %>